version: '3'

volumes:
  inmobapp_local_postgres_data: {}
  inmobapp_local_postgres_data_backups: {}

networks:
  local-network:
    external: true

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    networks:
      - local-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/frontend-vuetify:/usr/src/app
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=development
    networks:
      - local-network

  postgres:
    image: postgres:13-alpine
    volumes:
      - inmobapp_local_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_management
    ports:
      - "5432:5432"
    networks:
      - local-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - local-network
