version: '3'

volumes:
  inmobapp_local_postgres_data: {}
  inmobapp_local_postgres_data_backups: {}

networks:
  local-network:
    external: true

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - inmobapp_local_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_management
    ports:
      - "5432:5432"
    networks:
      - local-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - local-network
